# Generated by Django 5.1 on 2024-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_lot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
