# Generated by Django 5.1 on 2024-08-20 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_lot_app', '0002_alter_auctionlot_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 19, 14, 0, 6, 30901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
