# Generated by Django 5.1 on 2024-08-21 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_lot_app', '0003_alter_auctionlot_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='end_date',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
