# Generated by Django 5.1 on 2024-08-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_lot_app', '0004_alter_auctionlot_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
